#ifndef _DDI_EMI_ERRORDEFS_H
#define _DDI_EMI_ERRORDEFS_H

#include "../include/ddi_errordefs.h"


#define ERROR_DDI_EMI_SDRAM_NOT_SUPPORTED                        (ERROR_DDI_CLOCKS_GROUP)
#define ERROR_DDI_EMI_ENTER_SELF_REFRESH_TIMEOUT                 (ERROR_DDI_CLOCKS_GROUP + 1)
#define ERROR_DDI_EMI_EXIT_SELF_REFRESH_TIMEOUT                  (ERROR_DDI_CLOCKS_GROUP + 2)
#define ERROR_DDI_EMI_RESYNC_TIMEOUT                             (ERROR_DDI_CLOCKS_GROUP + 3)
#define ERROR_DDI_EMI_NO_CHIP_SELECT_WAS_SELECTED                (ERROR_DDI_CLOCKS_GROUP + 4)
#define ERROR_DDI_EMI_ONLY_2_CHIP_SELECTS_SUPPORTED 			 (ERROR_DDI_CLOCKS_GROUP + 5)
#define ERROR_DDI_EMI_64MB_PER_CHIP_SELCT_MAXIMUM 			     (ERROR_DDI_CLOCKS_GROUP + 6)
#define ERROR_DDI_EMI_UNEXPECTED_OBJECT_LOCATION                 (ERROR_DDI_CLOCKS_GROUP + 7)
#define ERROR_DDI_EMI_UNEXPECTED_OBJECT_SIZE                     (ERROR_DDI_CLOCKS_GROUP + 8)

#endif//_DDI_EMI_ERRORDEFS_H

