#ifndef _DDI_CLOCKS_ERRORDEFS_H
#define _DDI_CLOCKS_ERRORDEFS_H

#include "../include/ddi_errordefs.h"


#define ERROR_DDI_CLOCKS_GENERAL                                 (ERROR_DDI_CLOCKS_GROUP)
#define ERROR_DDI_CLOCKS_HCLK_SLOW_TOO_LOW                       (ERROR_DDI_CLOCKS_GROUP + 1)
#define ERROR_DDI_CLOCKS_HCLK_FAST_TOO_HIGH                      (ERROR_DDI_CLOCKS_GROUP + 2)
#define ERROR_DDI_CLOCKS_CANT_MEET_HCLK_CONSTRAINTS              (ERROR_DDI_CLOCKS_GROUP + 3)
#define ERROR_DDI_CLOCKS_PLL_OFF_BUT_NOT_BYPASSED                (ERROR_DDI_CLOCKS_GROUP + 4)

#define ERROR_DDI_CLOCKS_INVALID_PCLK_FREQ                       (ERROR_DDI_CLOCKS_GROUP)
#define ERROR_DDI_CLOCKS_INVALID_XCLK_FREQ                       (ERROR_DDI_CLOCKS_GROUP + 1)
#define ERROR_DDI_CLOCKS_INVALID_EMICLK_FREQ                     (ERROR_DDI_CLOCKS_GROUP + 2)
#define ERROR_DDI_CLOCKS_INVALID_PIXCLK_FREQ                     (ERROR_DDI_CLOCKS_GROUP + 3)
#define ERROR_DDI_CLOCKS_INVALID_PLL_FREQ                        (ERROR_DDI_CLOCKS_GROUP + 4)
#define ERROR_DDI_CLOCKS_INVALID_XTAL_FREQ                       (ERROR_DDI_CLOCKS_GROUP + 5)
#define ERROR_DDI_CLOCKS_INVALID_PFD_DIV                         (ERROR_DDI_CLOCKS_GROUP + 6)
#define ERROR_DDI_CLOCKS_INVALID_HCLK_DIV                        (ERROR_DDI_CLOCKS_GROUP + 7)
#define ERROR_DDI_CLOCKS_DIV_BY_ZERO                             (ERROR_DDI_CLOCKS_GROUP + 8)
#define ERROR_DDI_CLOCKS_ZERO_FREQ_REQUEST                       (ERROR_DDI_CLOCKS_GROUP + 9)

#endif//_DDI_CLOCKS_ERRORDEFS_H 

