
# emi module is copied to ocram in block (hw_emi, ddi_emi, hw_dram_settings)
# do not change the order

obj-y += ddi_clocks.o \
			ddi_clocks_dividers.o \
			ddi_clocks_gpmi.o \
			ddi_clocks_internal.o \
			ddi_clocks_misc.o \
			ddi_clocks_ir.o \
			ddi_clocks_pix.o \
			ddi_clocks_saif.o \
			ddi_clocks_spdif.o \
			ddi_clocks_ssp.o \
			ddi_clocks_xbus.o \
			ddi_clocks_pll.o \
			ddi_clocks_emi.o \
			hw_clocks.o \
			hw_clocks_gpmi.o \
			hw_clocks_init.o \
			hw_clocks_modules.o \
			hw_clocks_pll.o \
			hw_clocks_shutdown.o \
			hw_emi.o \
			ddi_emi.o \
			hw_dram_settings.o \
			
