
obj-y += \
	ddi_power.o \
	ddi_power_init.o \
	ddi_power_battery.o \
	ddi_power_handoff.o

obj-y +=  \
	hw_power.o \
	hw_power_init.o \
	hw_power_battery.o \
	hw_power_conversions.o \
	hw_power_registers.o \
	hw_power_5v_detect.o \
	hw_power_interrupts.o