/* Proximity */
/* 03-31-2008 : 21:58:25 */

/* This file is automatically generated by OneTouch Studio */
/* This file is very specific to a design */

/* ****************************************** */
/* ****************************************** */
/* ==> WARNING: ** DO NOT EDIT This file <==  */
/* ****************************************** */
/* ****************************************** */

//#ifdef      OT_LIB_VER_4_ABOVE
#if 0 //dhsong
                    /* NOTE: For OTLib 4.0 or above */

#ifndef _OTCONFIG_H
#define _OTCONFIG_H

//#include "OTCore.h"

#define OT_ADDR                         0x2C    /* OneTouch Device I2C Slave Address */

/* OneTouch Register Definitions */

#define OT_CONFIG_REG_START_ADDR        0x0000
#define OT_CONFIG_REG_END_ADDR          0x0032
#define OT_NUM_CONFIG_REG_BYTES         ((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
                                    /* Total number of Configuration Bytes */

#define OT_DATA_REG_START_ADDR          0x0109
#define OT_DATA_REG_END_ADDR            0x0109
#define OT_NUM_DATA_REG_BYTES           ((OT_DATA_REG_END_ADDR - OT_DATA_REG_START_ADDR + 1)*2)
                                    /* Total number of Data Bytes */

#define OT_DATA_REG_START_ADDR_HIGH     ((OT_DATA_REG_START_ADDR & 0xFF00)>>8)
#define OT_DATA_REG_START_ADDR_LOW      (OT_DATA_REG_START_ADDR & 0x00FF)


#define OT_BUTTON_DATA_REG_OFFSET       0
#define OT_BUTTON_HIGH_ELECTRODE        0
#define OT_BUTTON_LOW_ELECTRODE         6


#define OT_CONFIG_TABLE_ROWS            17

static OT_U8 OT_Config_Table[OT_CONFIG_TABLE_ROWS][4] = {
/* {address-high-byte, address-low-byte, data-hi-byte, data-lo-byte } */
{ 0x00, 0x00, 0x00, 0x07 },
{ 0x00, 0x01, 0x01, 0x00 },
{ 0x00, 0x04, 0x00, 0x7F },
{ 0x00, 0x10, 0xAA, 0xAA },
{ 0x00, 0x11, 0xAA, 0xAA },
{ 0x00, 0x12, 0xAA, 0xAA },
{ 0x00, 0x13, 0xAA, 0xDF },
{ 0x00, 0x1E, 0x00, 0x7F },
{ 0x00, 0x22, 0x00, 0x00 },
{ 0x00, 0x23, 0x00, 0x00 },
{ 0x00, 0x24, 0x00, 0x00 },
{ 0x00, 0x25, 0x00, 0x00 },
{ 0x00, 0x26, 0x00, 0x00 },
{ 0x00, 0x27, 0x00, 0x00 },
{ 0x00, 0x2B, 0x00, 0x00 },
{ 0x00, 0x30, 0x00, 0x40 },
{ 0x00, 0x32, 0x00, 0x7F },
{ 0x00, 0x0E, 0x7F, 0x00 }
};

#endif

#else
            /* NOTE: For OTLib 3.0 or earlier */

#ifndef _SYNAOTCONFIG_H
#define _SYNAOTCONFIG_H

#include "SynaOT.h"

//#define OT_ADDR                         0x2D    /* OneTouch Device I2C Slave Address */
#define OT_ADDR                         0x2C    /* OneTouch Device I2C Slave Address */

/* OneTouch Register Definitions */

#define OT_CONFIG_REG_START_ADDR        0x0000
//#define OT_CONFIG_REG_END_ADDR          0x0032
#define OT_CONFIG_REG_END_ADDR          0x0013 //reg addr, dhsong
#define OT_NUM_CONFIG_REG_BYTES         ((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
                                        /* Total number of Configuration Bytes */
#define OT_NUM_CONFIG_BYTES             (OT_NUM_CONFIG_REG_BYTES + 2)

static OT_U8    g_OT_Config[OT_NUM_CONFIG_BYTES]= {

                    /* High byte, followed by low Byte */
    0x00, 0x00,     /* base address of config registers */
    0x00, 0x07,     /* values of 0x0000 */
    0x00, 0x20,     /* values of 0x0001 */ //if this reg is modified, also set_touchpad_wakeup() func is modified
    0x00, 0x00,     /* values of 0x0002 */
    0x00, 0x00,     /* values of 0x0003 */
    0x00, 0x7F,     /* values of 0x0004 */
    0x00, 0x00,     /* values of 0x0005 */
    0x00, 0x00,     /* values of 0x0006 */
    0x00, 0x00,     /* values of 0x0007 */
    0x00, 0x00,     /* values of 0x0008 */
    0x00, 0x00,     /* values of 0x0009 */
    0x00, 0x00,     /* values of 0x000A */
    0x00, 0x00,     /* values of 0x000B */
    0x00, 0x00,     /* values of 0x000C */
    0x00, 0x00,     /* values of 0x000D */
    0x00, 0x00,     /* values of 0x000E */
    0x00, 0x00,     /* values of 0x000F */
    0xAA, 0xAA,     /* values of 0x0010 */ //sensitivity s1, s0
    0xAA, 0xAA,     /* values of 0x0011 */ //sensitivity s3, s2
    0xAA, 0xAA,     /* values of 0x0012 */ //sensitivity s5, s4
    0xAA, 0xAA      /* values of 0x0013 */ //sensitivity s7, s6
#if 0
    0x00, 0x00,     /* values of 0x0014 */
    0x00, 0x00,     /* values of 0x0015 */
    0x00, 0x00,     /* values of 0x0016 */
    0x00, 0x00,     /* values of 0x0017 */
    0x00, 0x00,     /* values of 0x0018 */
    0x00, 0x00,     /* values of 0x0019 */
    0x00, 0x00,     /* values of 0x001A */
    0x00, 0x00,     /* values of 0x001B */
    0x00, 0x00,     /* values of 0x001C */
    0x00, 0x00,     /* values of 0x001D */
    0x00, 0x7F,     /* values of 0x001E */
    0x00, 0x00,     /* values of 0x001F */
    0x00, 0x00,     /* values of 0x0020 */
    0x00, 0x00,     /* values of 0x0021 */
    0x00, 0x00,     /* values of 0x0022 */
    0x00, 0x00,     /* values of 0x0023 */
    0x00, 0x00,     /* values of 0x0024 */
    0x00, 0x00,     /* values of 0x0025 */
    0x00, 0x00,     /* values of 0x0026 */
    0x00, 0x00,     /* values of 0x0027 */
    0x00, 0x00,     /* values of 0x0028 */
    0x00, 0x00,     /* values of 0x0029 */
    0x00, 0x00,     /* values of 0x002A */
    0x00, 0x01,     /* values of 0x002B */
    0x00, 0x00,     /* values of 0x002C */
    0x00, 0x00,     /* values of 0x002D */
    0x00, 0x00,     /* values of 0x002E */
    0x00, 0x00,     /* values of 0x002F */
    0x00, 0x40,     /* values of 0x0030 */
    0x00, 0x00,     /* values of 0x0031 */
    0x00, 0x7F      /* values of 0x0032 */
#endif
};

#endif

#endif

