////////////////////////////////////////////////////////////////////////////////
//
// Filename: regslcdif.h
//
// Description: PIO Registers for LCDIF interface
//
// Xml Revision: 1.32
//
// Template revision: 3790
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) SigmaTel, Inc. Unpublished
//
// SigmaTel, Inc.
// Proprietary & Confidential
//
// This source code and the algorithms implemented therein constitute
// confidential information and may compromise trade secrets of SigmaTel, Inc.
// or its associates, and any unauthorized use thereof is prohibited.
//
////////////////////////////////////////////////////////////////////////////////
//
// WARNING!  THIS FILE IS AUTOMATICALLY GENERATED FROM XML.
//                DO NOT MODIFY THIS FILE DIRECTLY.
//
////////////////////////////////////////////////////////////////////////////////
//
// The following naming conventions are followed in this file.
//      XX_<module>_<regname>_<field>
//
// XX specifies the define / macro class
//      HW pertains to a register
//      BM indicates a Bit Mask
//      BF indicates a Bit Field macro
//
// <module> is the hardware module name which can be any of the following...
//      USB20 (Note when there is more than one copy of a given module, the
//      module name includes a number starting from 0 for the first instance
//      of that module)
//
// <regname> is the specific register within that module
//
// <field> is the specific bitfield within that <module>_<register>
//
// We also define the following...
//      hw_<module>_<regname>_t is typedef of anonymous union
//
////////////////////////////////////////////////////////////////////////////////

#ifndef _REGSLCDIF_H
#define _REGSLCDIF_H  1

#include "regs.h"

#ifndef REGS_LCDIF_BASE
#define REGS_LCDIF_BASE (REGS_BASE + 0x00030000)
#endif

////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_CTRL - LCDIF General Control Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        reg16_t  COUNT;
        unsigned RUN                  :  1;
        unsigned WORD_LENGTH          :  1;
        unsigned DATA_SELECT          :  1;
        unsigned DOTCLK_MODE          :  1;
        unsigned VSYNC_MODE           :  1;
        unsigned DATA_SWIZZLE         :  2;
        unsigned BYPASS_COUNT         :  1;
        unsigned DVI_MODE             :  1;
        unsigned SHIFT_NUM_BITS       :  2;
        unsigned DATA_SHIFT_DIR       :  1;
        unsigned WAIT_FOR_VSYNC_EDGE  :  1;
        unsigned READ_WRITEB          :  1;
        unsigned CLKGATE              :  1;
        unsigned SFTRST               :  1;
    } B;
} hw_lcdif_ctrl_t;
#endif


//
// constants & macros for entire HW_LCDIF_CTRL register
//

#define HW_LCDIF_CTRL_ADDR      (REGS_LCDIF_BASE + 0x00000000)
#define HW_LCDIF_CTRL_SET_ADDR  (REGS_LCDIF_BASE + 0x00000004)
#define HW_LCDIF_CTRL_CLR_ADDR  (REGS_LCDIF_BASE + 0x00000008)
#define HW_LCDIF_CTRL_TOG_ADDR  (REGS_LCDIF_BASE + 0x0000000C)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_CTRL           (*(volatile hw_lcdif_ctrl_t *) HW_LCDIF_CTRL_ADDR)
#define HW_LCDIF_CTRL_RD()      (HW_LCDIF_CTRL.U)
#define HW_LCDIF_CTRL_WR(v)     (HW_LCDIF_CTRL.U = (v))
#define HW_LCDIF_CTRL_SET(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL_SET_ADDR) = (v))
#define HW_LCDIF_CTRL_CLR(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL_CLR_ADDR) = (v))
#define HW_LCDIF_CTRL_TOG(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL_TOG_ADDR) = (v))
#endif


//
// constants & macros for individual HW_LCDIF_CTRL bitfields
//

//--- Register HW_LCDIF_CTRL, field SFTRST

#define BP_LCDIF_CTRL_SFTRST      31
#define BM_LCDIF_CTRL_SFTRST      0x80000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_CTRL_SFTRST(v)   ((((reg32_t) v) << 31) & BM_LCDIF_CTRL_SFTRST)
#else
#define BF_LCDIF_CTRL_SFTRST(v)   (((v) << 31) & BM_LCDIF_CTRL_SFTRST)
#endif

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_SFTRST(v)   BF_CS1(LCDIF_CTRL, SFTRST, v)
#endif

//--- Register HW_LCDIF_CTRL, field CLKGATE

#define BP_LCDIF_CTRL_CLKGATE      30
#define BM_LCDIF_CTRL_CLKGATE      0x40000000

#define BF_LCDIF_CTRL_CLKGATE(v)   (((v) << 30) & BM_LCDIF_CTRL_CLKGATE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_CLKGATE(v)   BF_CS1(LCDIF_CTRL, CLKGATE, v)
#endif

//--- Register HW_LCDIF_CTRL, field READ_WRITEB

#define BP_LCDIF_CTRL_READ_WRITEB      29
#define BM_LCDIF_CTRL_READ_WRITEB      0x20000000

#define BF_LCDIF_CTRL_READ_WRITEB(v)   (((v) << 29) & BM_LCDIF_CTRL_READ_WRITEB)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_READ_WRITEB(v)   BF_CS1(LCDIF_CTRL, READ_WRITEB, v)
#endif

//--- Register HW_LCDIF_CTRL, field WAIT_FOR_VSYNC_EDGE

#define BP_LCDIF_CTRL_WAIT_FOR_VSYNC_EDGE      28
#define BM_LCDIF_CTRL_WAIT_FOR_VSYNC_EDGE      0x10000000

#define BF_LCDIF_CTRL_WAIT_FOR_VSYNC_EDGE(v)   (((v) << 28) & BM_LCDIF_CTRL_WAIT_FOR_VSYNC_EDGE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_WAIT_FOR_VSYNC_EDGE(v)   BF_CS1(LCDIF_CTRL, WAIT_FOR_VSYNC_EDGE, v)
#endif

//--- Register HW_LCDIF_CTRL, field DATA_SHIFT_DIR

#define BP_LCDIF_CTRL_DATA_SHIFT_DIR      27
#define BM_LCDIF_CTRL_DATA_SHIFT_DIR      0x08000000

#define BF_LCDIF_CTRL_DATA_SHIFT_DIR(v)   (((v) << 27) & BM_LCDIF_CTRL_DATA_SHIFT_DIR)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_DATA_SHIFT_DIR(v)   BF_CS1(LCDIF_CTRL, DATA_SHIFT_DIR, v)
#endif

#define BV_LCDIF_CTRL_DATA_SHIFT_DIR__TXDATA_SHIFT_LEFT   0x0
#define BV_LCDIF_CTRL_DATA_SHIFT_DIR__TXDATA_SHIFT_RIGHT  0x1

//--- Register HW_LCDIF_CTRL, field SHIFT_NUM_BITS

#define BP_LCDIF_CTRL_SHIFT_NUM_BITS      25
#define BM_LCDIF_CTRL_SHIFT_NUM_BITS      0x06000000

#define BF_LCDIF_CTRL_SHIFT_NUM_BITS(v)   (((v) << 25) & BM_LCDIF_CTRL_SHIFT_NUM_BITS)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_SHIFT_NUM_BITS(v)   BF_CS1(LCDIF_CTRL, SHIFT_NUM_BITS, v)
#endif

//--- Register HW_LCDIF_CTRL, field DVI_MODE

#define BP_LCDIF_CTRL_DVI_MODE      24
#define BM_LCDIF_CTRL_DVI_MODE      0x01000000

#define BF_LCDIF_CTRL_DVI_MODE(v)   (((v) << 24) & BM_LCDIF_CTRL_DVI_MODE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_DVI_MODE(v)   BF_CS1(LCDIF_CTRL, DVI_MODE, v)
#endif

//--- Register HW_LCDIF_CTRL, field BYPASS_COUNT

#define BP_LCDIF_CTRL_BYPASS_COUNT      23
#define BM_LCDIF_CTRL_BYPASS_COUNT      0x00800000

#define BF_LCDIF_CTRL_BYPASS_COUNT(v)   (((v) << 23) & BM_LCDIF_CTRL_BYPASS_COUNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_BYPASS_COUNT(v)   BF_CS1(LCDIF_CTRL, BYPASS_COUNT, v)
#endif

//--- Register HW_LCDIF_CTRL, field DATA_SWIZZLE

#define BP_LCDIF_CTRL_DATA_SWIZZLE      21
#define BM_LCDIF_CTRL_DATA_SWIZZLE      0x00600000

#define BF_LCDIF_CTRL_DATA_SWIZZLE(v)   (((v) << 21) & BM_LCDIF_CTRL_DATA_SWIZZLE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_DATA_SWIZZLE(v)   BF_CS1(LCDIF_CTRL, DATA_SWIZZLE, v)
#endif

#define BV_LCDIF_CTRL_DATA_SWIZZLE__NO_SWAP          0x0
#define BV_LCDIF_CTRL_DATA_SWIZZLE__LITTLE_ENDIAN    0x0
#define BV_LCDIF_CTRL_DATA_SWIZZLE__BIG_ENDIAN_SWAP  0x1
#define BV_LCDIF_CTRL_DATA_SWIZZLE__SWAP_ALL_BYTES   0x1
#define BV_LCDIF_CTRL_DATA_SWIZZLE__HWD_SWAP         0x2
#define BV_LCDIF_CTRL_DATA_SWIZZLE__HWD_BYTE_SWAP    0x3

//--- Register HW_LCDIF_CTRL, field VSYNC_MODE

#define BP_LCDIF_CTRL_VSYNC_MODE      20
#define BM_LCDIF_CTRL_VSYNC_MODE      0x00100000

#define BF_LCDIF_CTRL_VSYNC_MODE(v)   (((v) << 20) & BM_LCDIF_CTRL_VSYNC_MODE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_VSYNC_MODE(v)   BF_CS1(LCDIF_CTRL, VSYNC_MODE, v)
#endif

//--- Register HW_LCDIF_CTRL, field DOTCLK_MODE

#define BP_LCDIF_CTRL_DOTCLK_MODE      19
#define BM_LCDIF_CTRL_DOTCLK_MODE      0x00080000

#define BF_LCDIF_CTRL_DOTCLK_MODE(v)   (((v) << 19) & BM_LCDIF_CTRL_DOTCLK_MODE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_DOTCLK_MODE(v)   BF_CS1(LCDIF_CTRL, DOTCLK_MODE, v)
#endif

//--- Register HW_LCDIF_CTRL, field DATA_SELECT

#define BP_LCDIF_CTRL_DATA_SELECT      18
#define BM_LCDIF_CTRL_DATA_SELECT      0x00040000

#define BF_LCDIF_CTRL_DATA_SELECT(v)   (((v) << 18) & BM_LCDIF_CTRL_DATA_SELECT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_DATA_SELECT(v)   BF_CS1(LCDIF_CTRL, DATA_SELECT, v)
#endif

#define BV_LCDIF_CTRL_DATA_SELECT__CMD_MODE   0x0
#define BV_LCDIF_CTRL_DATA_SELECT__DATA_MODE  0x1

//--- Register HW_LCDIF_CTRL, field WORD_LENGTH

#define BP_LCDIF_CTRL_WORD_LENGTH      17
#define BM_LCDIF_CTRL_WORD_LENGTH      0x00020000

#define BF_LCDIF_CTRL_WORD_LENGTH(v)   (((v) << 17) & BM_LCDIF_CTRL_WORD_LENGTH)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_WORD_LENGTH(v)   BF_CS1(LCDIF_CTRL, WORD_LENGTH, v)
#endif

#define BV_LCDIF_CTRL_WORD_LENGTH__16_BIT  0x0
#define BV_LCDIF_CTRL_WORD_LENGTH__8_BIT   0x1

//--- Register HW_LCDIF_CTRL, field RUN

#define BP_LCDIF_CTRL_RUN      16
#define BM_LCDIF_CTRL_RUN      0x00010000

#define BF_LCDIF_CTRL_RUN(v)   (((v) << 16) & BM_LCDIF_CTRL_RUN)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_RUN(v)   BF_CS1(LCDIF_CTRL, RUN, v)
#endif

//--- Register HW_LCDIF_CTRL, field COUNT

#define BP_LCDIF_CTRL_COUNT      0
#define BM_LCDIF_CTRL_COUNT      0x0000FFFF

#define BF_LCDIF_CTRL_COUNT(v)   (((v) << 0) & BM_LCDIF_CTRL_COUNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL_COUNT(v)   (HW_LCDIF_CTRL.B.COUNT = (v))
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_CTRL1 - LCDIF General Control1 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned RESET                          :  1;
        unsigned MODE86                         :  1;
        unsigned BUSY_ENABLE                    :  1;
        unsigned LCD_CS_CTRL                    :  1;
        unsigned FIRST_READ_DUMMY               :  1;
        unsigned READ_MODE_NUM_PACKED_SUBWORDS  :  3;
        unsigned VSYNC_EDGE_IRQ                 :  1;
        unsigned CUR_FRAME_DONE_IRQ             :  1;
        unsigned UNDERFLOW_IRQ                  :  1;
        unsigned OVERFLOW_IRQ                   :  1;
        unsigned VSYNC_EDGE_IRQ_EN              :  1;
        unsigned CUR_FRAME_DONE_IRQ_EN          :  1;
        unsigned UNDERFLOW_IRQ_EN               :  1;
        unsigned OVERFLOW_IRQ_EN                :  1;
        unsigned BYTE_PACKING_FORMAT            :  4;
        unsigned RSRVD0                         : 12;
    } B;
} hw_lcdif_ctrl1_t;
#endif


//
// constants & macros for entire HW_LCDIF_CTRL1 register
//

#define HW_LCDIF_CTRL1_ADDR      (REGS_LCDIF_BASE + 0x00000010)
#define HW_LCDIF_CTRL1_SET_ADDR  (REGS_LCDIF_BASE + 0x00000014)
#define HW_LCDIF_CTRL1_CLR_ADDR  (REGS_LCDIF_BASE + 0x00000018)
#define HW_LCDIF_CTRL1_TOG_ADDR  (REGS_LCDIF_BASE + 0x0000001C)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_CTRL1           (*(volatile hw_lcdif_ctrl1_t *) HW_LCDIF_CTRL1_ADDR)
#define HW_LCDIF_CTRL1_RD()      (HW_LCDIF_CTRL1.U)
#define HW_LCDIF_CTRL1_WR(v)     (HW_LCDIF_CTRL1.U = (v))
#define HW_LCDIF_CTRL1_SET(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL1_SET_ADDR) = (v))
#define HW_LCDIF_CTRL1_CLR(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL1_CLR_ADDR) = (v))
#define HW_LCDIF_CTRL1_TOG(v)    ((*(volatile reg32_t *) HW_LCDIF_CTRL1_TOG_ADDR) = (v))
#endif


//
// constants & macros for individual HW_LCDIF_CTRL1 bitfields
//

//--- Register HW_LCDIF_CTRL1, field BYTE_PACKING_FORMAT

#define BP_LCDIF_CTRL1_BYTE_PACKING_FORMAT      16
#define BM_LCDIF_CTRL1_BYTE_PACKING_FORMAT      0x000F0000

#define BF_LCDIF_CTRL1_BYTE_PACKING_FORMAT(v)   (((v) << 16) & BM_LCDIF_CTRL1_BYTE_PACKING_FORMAT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_BYTE_PACKING_FORMAT(v)   BF_CS1(LCDIF_CTRL1, BYTE_PACKING_FORMAT, v)
#endif

//--- Register HW_LCDIF_CTRL1, field OVERFLOW_IRQ_EN

#define BP_LCDIF_CTRL1_OVERFLOW_IRQ_EN      15
#define BM_LCDIF_CTRL1_OVERFLOW_IRQ_EN      0x00008000

#define BF_LCDIF_CTRL1_OVERFLOW_IRQ_EN(v)   (((v) << 15) & BM_LCDIF_CTRL1_OVERFLOW_IRQ_EN)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_OVERFLOW_IRQ_EN(v)   BF_CS1(LCDIF_CTRL1, OVERFLOW_IRQ_EN, v)
#endif

//--- Register HW_LCDIF_CTRL1, field UNDERFLOW_IRQ_EN

#define BP_LCDIF_CTRL1_UNDERFLOW_IRQ_EN      14
#define BM_LCDIF_CTRL1_UNDERFLOW_IRQ_EN      0x00004000

#define BF_LCDIF_CTRL1_UNDERFLOW_IRQ_EN(v)   (((v) << 14) & BM_LCDIF_CTRL1_UNDERFLOW_IRQ_EN)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_UNDERFLOW_IRQ_EN(v)   BF_CS1(LCDIF_CTRL1, UNDERFLOW_IRQ_EN, v)
#endif

//--- Register HW_LCDIF_CTRL1, field CUR_FRAME_DONE_IRQ_EN

#define BP_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ_EN      13
#define BM_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ_EN      0x00002000

#define BF_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ_EN(v)   (((v) << 13) & BM_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ_EN)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ_EN(v)   BF_CS1(LCDIF_CTRL1, CUR_FRAME_DONE_IRQ_EN, v)
#endif

//--- Register HW_LCDIF_CTRL1, field VSYNC_EDGE_IRQ_EN

#define BP_LCDIF_CTRL1_VSYNC_EDGE_IRQ_EN      12
#define BM_LCDIF_CTRL1_VSYNC_EDGE_IRQ_EN      0x00001000

#define BF_LCDIF_CTRL1_VSYNC_EDGE_IRQ_EN(v)   (((v) << 12) & BM_LCDIF_CTRL1_VSYNC_EDGE_IRQ_EN)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_VSYNC_EDGE_IRQ_EN(v)   BF_CS1(LCDIF_CTRL1, VSYNC_EDGE_IRQ_EN, v)
#endif

//--- Register HW_LCDIF_CTRL1, field OVERFLOW_IRQ

#define BP_LCDIF_CTRL1_OVERFLOW_IRQ      11
#define BM_LCDIF_CTRL1_OVERFLOW_IRQ      0x00000800

#define BF_LCDIF_CTRL1_OVERFLOW_IRQ(v)   (((v) << 11) & BM_LCDIF_CTRL1_OVERFLOW_IRQ)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_OVERFLOW_IRQ(v)   BF_CS1(LCDIF_CTRL1, OVERFLOW_IRQ, v)
#endif

#define BV_LCDIF_CTRL1_OVERFLOW_IRQ__NO_REQUEST  0x0
#define BV_LCDIF_CTRL1_OVERFLOW_IRQ__REQUEST     0x1

//--- Register HW_LCDIF_CTRL1, field UNDERFLOW_IRQ

#define BP_LCDIF_CTRL1_UNDERFLOW_IRQ      10
#define BM_LCDIF_CTRL1_UNDERFLOW_IRQ      0x00000400

#define BF_LCDIF_CTRL1_UNDERFLOW_IRQ(v)   (((v) << 10) & BM_LCDIF_CTRL1_UNDERFLOW_IRQ)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_UNDERFLOW_IRQ(v)   BF_CS1(LCDIF_CTRL1, UNDERFLOW_IRQ, v)
#endif

#define BV_LCDIF_CTRL1_UNDERFLOW_IRQ__NO_REQUEST  0x0
#define BV_LCDIF_CTRL1_UNDERFLOW_IRQ__REQUEST     0x1

//--- Register HW_LCDIF_CTRL1, field CUR_FRAME_DONE_IRQ

#define BP_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ      9
#define BM_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ      0x00000200

#define BF_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ(v)   (((v) << 9) & BM_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ(v)   BF_CS1(LCDIF_CTRL1, CUR_FRAME_DONE_IRQ, v)
#endif

#define BV_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ__NO_REQUEST  0x0
#define BV_LCDIF_CTRL1_CUR_FRAME_DONE_IRQ__REQUEST     0x1

//--- Register HW_LCDIF_CTRL1, field VSYNC_EDGE_IRQ

#define BP_LCDIF_CTRL1_VSYNC_EDGE_IRQ      8
#define BM_LCDIF_CTRL1_VSYNC_EDGE_IRQ      0x00000100

#define BF_LCDIF_CTRL1_VSYNC_EDGE_IRQ(v)   (((v) << 8) & BM_LCDIF_CTRL1_VSYNC_EDGE_IRQ)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_VSYNC_EDGE_IRQ(v)   BF_CS1(LCDIF_CTRL1, VSYNC_EDGE_IRQ, v)
#endif

#define BV_LCDIF_CTRL1_VSYNC_EDGE_IRQ__NO_REQUEST  0x0
#define BV_LCDIF_CTRL1_VSYNC_EDGE_IRQ__REQUEST     0x1

//--- Register HW_LCDIF_CTRL1, field READ_MODE_NUM_PACKED_SUBWORDS

#define BP_LCDIF_CTRL1_READ_MODE_NUM_PACKED_SUBWORDS      5
#define BM_LCDIF_CTRL1_READ_MODE_NUM_PACKED_SUBWORDS      0x000000E0

#define BF_LCDIF_CTRL1_READ_MODE_NUM_PACKED_SUBWORDS(v)   (((v) << 5) & BM_LCDIF_CTRL1_READ_MODE_NUM_PACKED_SUBWORDS)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_READ_MODE_NUM_PACKED_SUBWORDS(v)   BF_CS1(LCDIF_CTRL1, READ_MODE_NUM_PACKED_SUBWORDS, v)
#endif

//--- Register HW_LCDIF_CTRL1, field FIRST_READ_DUMMY

#define BP_LCDIF_CTRL1_FIRST_READ_DUMMY      4
#define BM_LCDIF_CTRL1_FIRST_READ_DUMMY      0x00000010

#define BF_LCDIF_CTRL1_FIRST_READ_DUMMY(v)   (((v) << 4) & BM_LCDIF_CTRL1_FIRST_READ_DUMMY)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_FIRST_READ_DUMMY(v)   BF_CS1(LCDIF_CTRL1, FIRST_READ_DUMMY, v)
#endif

//--- Register HW_LCDIF_CTRL1, field LCD_CS_CTRL

#define BP_LCDIF_CTRL1_LCD_CS_CTRL      3
#define BM_LCDIF_CTRL1_LCD_CS_CTRL      0x00000008

#define BF_LCDIF_CTRL1_LCD_CS_CTRL(v)   (((v) << 3) & BM_LCDIF_CTRL1_LCD_CS_CTRL)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_LCD_CS_CTRL(v)   BF_CS1(LCDIF_CTRL1, LCD_CS_CTRL, v)
#endif

//--- Register HW_LCDIF_CTRL1, field BUSY_ENABLE

#define BP_LCDIF_CTRL1_BUSY_ENABLE      2
#define BM_LCDIF_CTRL1_BUSY_ENABLE      0x00000004

#define BF_LCDIF_CTRL1_BUSY_ENABLE(v)   (((v) << 2) & BM_LCDIF_CTRL1_BUSY_ENABLE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_BUSY_ENABLE(v)   BF_CS1(LCDIF_CTRL1, BUSY_ENABLE, v)
#endif

#define BV_LCDIF_CTRL1_BUSY_ENABLE__BUSY_DISABLED  0x0
#define BV_LCDIF_CTRL1_BUSY_ENABLE__BUSY_ENABLED   0x1

//--- Register HW_LCDIF_CTRL1, field MODE86

#define BP_LCDIF_CTRL1_MODE86      1
#define BM_LCDIF_CTRL1_MODE86      0x00000002

#define BF_LCDIF_CTRL1_MODE86(v)   (((v) << 1) & BM_LCDIF_CTRL1_MODE86)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_MODE86(v)   BF_CS1(LCDIF_CTRL1, MODE86, v)
#endif

#define BV_LCDIF_CTRL1_MODE86__8080_MODE  0x0
#define BV_LCDIF_CTRL1_MODE86__6800_MODE  0x1

//--- Register HW_LCDIF_CTRL1, field RESET

#define BP_LCDIF_CTRL1_RESET      0
#define BM_LCDIF_CTRL1_RESET      0x00000001

#define BF_LCDIF_CTRL1_RESET(v)   (((v) << 0) & BM_LCDIF_CTRL1_RESET)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_CTRL1_RESET(v)   BF_CS1(LCDIF_CTRL1, RESET, v)
#endif

#define BV_LCDIF_CTRL1_RESET__LCDRESET_LOW   0x0
#define BV_LCDIF_CTRL1_RESET__LCDRESET_HIGH  0x1


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_TIMING - LCD Interface Timing Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        reg8_t   DATA_SETUP;
        reg8_t   DATA_HOLD;
        reg8_t   CMD_SETUP;
        reg8_t   CMD_HOLD;
    } B;
} hw_lcdif_timing_t;
#endif


//
// constants & macros for entire HW_LCDIF_TIMING register
//

#define HW_LCDIF_TIMING_ADDR      (REGS_LCDIF_BASE + 0x00000020)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_TIMING           (*(volatile hw_lcdif_timing_t *) HW_LCDIF_TIMING_ADDR)
#define HW_LCDIF_TIMING_RD()      (HW_LCDIF_TIMING.U)
#define HW_LCDIF_TIMING_WR(v)     (HW_LCDIF_TIMING.U = (v))
#define HW_LCDIF_TIMING_SET(v)    (HW_LCDIF_TIMING_WR(HW_LCDIF_TIMING_RD() |  (v)))
#define HW_LCDIF_TIMING_CLR(v)    (HW_LCDIF_TIMING_WR(HW_LCDIF_TIMING_RD() & ~(v)))
#define HW_LCDIF_TIMING_TOG(v)    (HW_LCDIF_TIMING_WR(HW_LCDIF_TIMING_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_TIMING bitfields
//

//--- Register HW_LCDIF_TIMING, field CMD_HOLD

#define BP_LCDIF_TIMING_CMD_HOLD      24
#define BM_LCDIF_TIMING_CMD_HOLD      0xFF000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_TIMING_CMD_HOLD(v)   ((((reg32_t) v) << 24) & BM_LCDIF_TIMING_CMD_HOLD)
#else
#define BF_LCDIF_TIMING_CMD_HOLD(v)   (((v) << 24) & BM_LCDIF_TIMING_CMD_HOLD)
#endif

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_TIMING_CMD_HOLD(v)   (HW_LCDIF_TIMING.B.CMD_HOLD = (v))
#endif

//--- Register HW_LCDIF_TIMING, field CMD_SETUP

#define BP_LCDIF_TIMING_CMD_SETUP      16
#define BM_LCDIF_TIMING_CMD_SETUP      0x00FF0000

#define BF_LCDIF_TIMING_CMD_SETUP(v)   (((v) << 16) & BM_LCDIF_TIMING_CMD_SETUP)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_TIMING_CMD_SETUP(v)   (HW_LCDIF_TIMING.B.CMD_SETUP = (v))
#endif

//--- Register HW_LCDIF_TIMING, field DATA_HOLD

#define BP_LCDIF_TIMING_DATA_HOLD      8
#define BM_LCDIF_TIMING_DATA_HOLD      0x0000FF00

#define BF_LCDIF_TIMING_DATA_HOLD(v)   (((v) << 8) & BM_LCDIF_TIMING_DATA_HOLD)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_TIMING_DATA_HOLD(v)   (HW_LCDIF_TIMING.B.DATA_HOLD = (v))
#endif

//--- Register HW_LCDIF_TIMING, field DATA_SETUP

#define BP_LCDIF_TIMING_DATA_SETUP      0
#define BM_LCDIF_TIMING_DATA_SETUP      0x000000FF

#define BF_LCDIF_TIMING_DATA_SETUP(v)   (((v) << 0) & BM_LCDIF_TIMING_DATA_SETUP)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_TIMING_DATA_SETUP(v)   (HW_LCDIF_TIMING.B.DATA_SETUP = (v))
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_VDCTRL0 - LCDIF VSYNC Mode and Dotclk Mode Control Register0
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned DOTCLK_V_VALID_DATA_CNT  : 10;
        unsigned RSRVD1                   :  9;
        unsigned INTERLACE                :  1;
        unsigned VSYNC_PULSE_WIDTH_UNIT   :  1;
        unsigned VSYNC_PERIOD_UNIT        :  1;
        unsigned RSRVD2                   :  2;
        unsigned ENABLE_POL               :  1;
        unsigned DOTCLK_POL               :  1;
        unsigned HSYNC_POL                :  1;
        unsigned VSYNC_POL                :  1;
        unsigned ENABLE_PRESENT           :  1;
        unsigned VSYNC_OEB                :  1;
        unsigned RSRVD3                   :  2;
    } B;
} hw_lcdif_vdctrl0_t;
#endif


//
// constants & macros for entire HW_LCDIF_VDCTRL0 register
//

#define HW_LCDIF_VDCTRL0_ADDR      (REGS_LCDIF_BASE + 0x00000030)
#define HW_LCDIF_VDCTRL0_SET_ADDR  (REGS_LCDIF_BASE + 0x00000034)
#define HW_LCDIF_VDCTRL0_CLR_ADDR  (REGS_LCDIF_BASE + 0x00000038)
#define HW_LCDIF_VDCTRL0_TOG_ADDR  (REGS_LCDIF_BASE + 0x0000003C)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_VDCTRL0           (*(volatile hw_lcdif_vdctrl0_t *) HW_LCDIF_VDCTRL0_ADDR)
#define HW_LCDIF_VDCTRL0_RD()      (HW_LCDIF_VDCTRL0.U)
#define HW_LCDIF_VDCTRL0_WR(v)     (HW_LCDIF_VDCTRL0.U = (v))
#define HW_LCDIF_VDCTRL0_SET(v)    ((*(volatile reg32_t *) HW_LCDIF_VDCTRL0_SET_ADDR) = (v))
#define HW_LCDIF_VDCTRL0_CLR(v)    ((*(volatile reg32_t *) HW_LCDIF_VDCTRL0_CLR_ADDR) = (v))
#define HW_LCDIF_VDCTRL0_TOG(v)    ((*(volatile reg32_t *) HW_LCDIF_VDCTRL0_TOG_ADDR) = (v))
#endif


//
// constants & macros for individual HW_LCDIF_VDCTRL0 bitfields
//

//--- Register HW_LCDIF_VDCTRL0, field VSYNC_OEB

#define BP_LCDIF_VDCTRL0_VSYNC_OEB      29
#define BM_LCDIF_VDCTRL0_VSYNC_OEB      0x20000000

#define BF_LCDIF_VDCTRL0_VSYNC_OEB(v)   (((v) << 29) & BM_LCDIF_VDCTRL0_VSYNC_OEB)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_VSYNC_OEB(v)   BF_CS1(LCDIF_VDCTRL0, VSYNC_OEB, v)
#endif

#define BV_LCDIF_VDCTRL0_VSYNC_OEB__VSYNC_OUTPUT  0x0
#define BV_LCDIF_VDCTRL0_VSYNC_OEB__VSYNC_INPUT   0x1

//--- Register HW_LCDIF_VDCTRL0, field ENABLE_PRESENT

#define BP_LCDIF_VDCTRL0_ENABLE_PRESENT      28
#define BM_LCDIF_VDCTRL0_ENABLE_PRESENT      0x10000000

#define BF_LCDIF_VDCTRL0_ENABLE_PRESENT(v)   (((v) << 28) & BM_LCDIF_VDCTRL0_ENABLE_PRESENT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_ENABLE_PRESENT(v)   BF_CS1(LCDIF_VDCTRL0, ENABLE_PRESENT, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field VSYNC_POL

#define BP_LCDIF_VDCTRL0_VSYNC_POL      27
#define BM_LCDIF_VDCTRL0_VSYNC_POL      0x08000000

#define BF_LCDIF_VDCTRL0_VSYNC_POL(v)   (((v) << 27) & BM_LCDIF_VDCTRL0_VSYNC_POL)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_VSYNC_POL(v)   BF_CS1(LCDIF_VDCTRL0, VSYNC_POL, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field HSYNC_POL

#define BP_LCDIF_VDCTRL0_HSYNC_POL      26
#define BM_LCDIF_VDCTRL0_HSYNC_POL      0x04000000

#define BF_LCDIF_VDCTRL0_HSYNC_POL(v)   (((v) << 26) & BM_LCDIF_VDCTRL0_HSYNC_POL)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_HSYNC_POL(v)   BF_CS1(LCDIF_VDCTRL0, HSYNC_POL, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field DOTCLK_POL

#define BP_LCDIF_VDCTRL0_DOTCLK_POL      25
#define BM_LCDIF_VDCTRL0_DOTCLK_POL      0x02000000

#define BF_LCDIF_VDCTRL0_DOTCLK_POL(v)   (((v) << 25) & BM_LCDIF_VDCTRL0_DOTCLK_POL)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_DOTCLK_POL(v)   BF_CS1(LCDIF_VDCTRL0, DOTCLK_POL, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field ENABLE_POL

#define BP_LCDIF_VDCTRL0_ENABLE_POL      24
#define BM_LCDIF_VDCTRL0_ENABLE_POL      0x01000000

#define BF_LCDIF_VDCTRL0_ENABLE_POL(v)   (((v) << 24) & BM_LCDIF_VDCTRL0_ENABLE_POL)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_ENABLE_POL(v)   BF_CS1(LCDIF_VDCTRL0, ENABLE_POL, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field VSYNC_PERIOD_UNIT

#define BP_LCDIF_VDCTRL0_VSYNC_PERIOD_UNIT      21
#define BM_LCDIF_VDCTRL0_VSYNC_PERIOD_UNIT      0x00200000

#define BF_LCDIF_VDCTRL0_VSYNC_PERIOD_UNIT(v)   (((v) << 21) & BM_LCDIF_VDCTRL0_VSYNC_PERIOD_UNIT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_VSYNC_PERIOD_UNIT(v)   BF_CS1(LCDIF_VDCTRL0, VSYNC_PERIOD_UNIT, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field VSYNC_PULSE_WIDTH_UNIT

#define BP_LCDIF_VDCTRL0_VSYNC_PULSE_WIDTH_UNIT      20
#define BM_LCDIF_VDCTRL0_VSYNC_PULSE_WIDTH_UNIT      0x00100000

#define BF_LCDIF_VDCTRL0_VSYNC_PULSE_WIDTH_UNIT(v)   (((v) << 20) & BM_LCDIF_VDCTRL0_VSYNC_PULSE_WIDTH_UNIT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_VSYNC_PULSE_WIDTH_UNIT(v)   BF_CS1(LCDIF_VDCTRL0, VSYNC_PULSE_WIDTH_UNIT, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field INTERLACE

#define BP_LCDIF_VDCTRL0_INTERLACE      19
#define BM_LCDIF_VDCTRL0_INTERLACE      0x00080000

#define BF_LCDIF_VDCTRL0_INTERLACE(v)   (((v) << 19) & BM_LCDIF_VDCTRL0_INTERLACE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_INTERLACE(v)   BF_CS1(LCDIF_VDCTRL0, INTERLACE, v)
#endif

//--- Register HW_LCDIF_VDCTRL0, field DOTCLK_V_VALID_DATA_CNT

#define BP_LCDIF_VDCTRL0_DOTCLK_V_VALID_DATA_CNT      0
#define BM_LCDIF_VDCTRL0_DOTCLK_V_VALID_DATA_CNT      0x000003FF

#define BF_LCDIF_VDCTRL0_DOTCLK_V_VALID_DATA_CNT(v)   (((v) << 0) & BM_LCDIF_VDCTRL0_DOTCLK_V_VALID_DATA_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL0_DOTCLK_V_VALID_DATA_CNT(v)   BF_CS1(LCDIF_VDCTRL0, DOTCLK_V_VALID_DATA_CNT, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_VDCTRL1 - LCDIF VSYNC Mode and Dotclk Mode Control Register1
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned VSYNC_PERIOD       : 20;
        unsigned VSYNC_PULSE_WIDTH  : 12;
    } B;
} hw_lcdif_vdctrl1_t;
#endif


//
// constants & macros for entire HW_LCDIF_VDCTRL1 register
//

#define HW_LCDIF_VDCTRL1_ADDR      (REGS_LCDIF_BASE + 0x00000040)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_VDCTRL1           (*(volatile hw_lcdif_vdctrl1_t *) HW_LCDIF_VDCTRL1_ADDR)
#define HW_LCDIF_VDCTRL1_RD()      (HW_LCDIF_VDCTRL1.U)
#define HW_LCDIF_VDCTRL1_WR(v)     (HW_LCDIF_VDCTRL1.U = (v))
#define HW_LCDIF_VDCTRL1_SET(v)    (HW_LCDIF_VDCTRL1_WR(HW_LCDIF_VDCTRL1_RD() |  (v)))
#define HW_LCDIF_VDCTRL1_CLR(v)    (HW_LCDIF_VDCTRL1_WR(HW_LCDIF_VDCTRL1_RD() & ~(v)))
#define HW_LCDIF_VDCTRL1_TOG(v)    (HW_LCDIF_VDCTRL1_WR(HW_LCDIF_VDCTRL1_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_VDCTRL1 bitfields
//

//--- Register HW_LCDIF_VDCTRL1, field VSYNC_PULSE_WIDTH

#define BP_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH      20
#define BM_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH      0xFFF00000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH(v)   ((((reg32_t) v) << 20) & BM_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH)
#else
#define BF_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH(v)   (((v) << 20) & BM_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH)
#endif

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL1_VSYNC_PULSE_WIDTH(v)   BF_CS1(LCDIF_VDCTRL1, VSYNC_PULSE_WIDTH, v)
#endif

//--- Register HW_LCDIF_VDCTRL1, field VSYNC_PERIOD

#define BP_LCDIF_VDCTRL1_VSYNC_PERIOD      0
#define BM_LCDIF_VDCTRL1_VSYNC_PERIOD      0x000FFFFF

#define BF_LCDIF_VDCTRL1_VSYNC_PERIOD(v)   (((v) << 0) & BM_LCDIF_VDCTRL1_VSYNC_PERIOD)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL1_VSYNC_PERIOD(v)   BF_CS1(LCDIF_VDCTRL1, VSYNC_PERIOD, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_VDCTRL2 - LCDIF VSYNC Mode and Dotclk Mode Control Register2
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned DOTCLK_H_VALID_DATA_CNT  : 11;
        unsigned HSYNC_PERIOD             : 12;
        unsigned HSYNC_PULSE_WIDTH        :  9;
    } B;
} hw_lcdif_vdctrl2_t;
#endif


//
// constants & macros for entire HW_LCDIF_VDCTRL2 register
//

#define HW_LCDIF_VDCTRL2_ADDR      (REGS_LCDIF_BASE + 0x00000050)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_VDCTRL2           (*(volatile hw_lcdif_vdctrl2_t *) HW_LCDIF_VDCTRL2_ADDR)
#define HW_LCDIF_VDCTRL2_RD()      (HW_LCDIF_VDCTRL2.U)
#define HW_LCDIF_VDCTRL2_WR(v)     (HW_LCDIF_VDCTRL2.U = (v))
#define HW_LCDIF_VDCTRL2_SET(v)    (HW_LCDIF_VDCTRL2_WR(HW_LCDIF_VDCTRL2_RD() |  (v)))
#define HW_LCDIF_VDCTRL2_CLR(v)    (HW_LCDIF_VDCTRL2_WR(HW_LCDIF_VDCTRL2_RD() & ~(v)))
#define HW_LCDIF_VDCTRL2_TOG(v)    (HW_LCDIF_VDCTRL2_WR(HW_LCDIF_VDCTRL2_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_VDCTRL2 bitfields
//

//--- Register HW_LCDIF_VDCTRL2, field HSYNC_PULSE_WIDTH

#define BP_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH      23
#define BM_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH      0xFF800000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH(v)   ((((reg32_t) v) << 23) & BM_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH)
#else
#define BF_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH(v)   (((v) << 23) & BM_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH)
#endif

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL2_HSYNC_PULSE_WIDTH(v)   BF_CS1(LCDIF_VDCTRL2, HSYNC_PULSE_WIDTH, v)
#endif

//--- Register HW_LCDIF_VDCTRL2, field HSYNC_PERIOD

#define BP_LCDIF_VDCTRL2_HSYNC_PERIOD      11
#define BM_LCDIF_VDCTRL2_HSYNC_PERIOD      0x007FF800

#define BF_LCDIF_VDCTRL2_HSYNC_PERIOD(v)   (((v) << 11) & BM_LCDIF_VDCTRL2_HSYNC_PERIOD)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL2_HSYNC_PERIOD(v)   BF_CS1(LCDIF_VDCTRL2, HSYNC_PERIOD, v)
#endif

//--- Register HW_LCDIF_VDCTRL2, field DOTCLK_H_VALID_DATA_CNT

#define BP_LCDIF_VDCTRL2_DOTCLK_H_VALID_DATA_CNT      0
#define BM_LCDIF_VDCTRL2_DOTCLK_H_VALID_DATA_CNT      0x000007FF

#define BF_LCDIF_VDCTRL2_DOTCLK_H_VALID_DATA_CNT(v)   (((v) << 0) & BM_LCDIF_VDCTRL2_DOTCLK_H_VALID_DATA_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL2_DOTCLK_H_VALID_DATA_CNT(v)   BF_CS1(LCDIF_VDCTRL2, DOTCLK_H_VALID_DATA_CNT, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_VDCTRL3 - LCDIF VSYNC Mode and Dotclk Mode Control Register3
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned VERTICAL_WAIT_CNT    :  9;
        unsigned RSRVD1               :  3;
        unsigned HORIZONTAL_WAIT_CNT  : 12;
        unsigned SYNC_SIGNALS_ON      :  1;
        unsigned RSRVD0               :  7;
    } B;
} hw_lcdif_vdctrl3_t;
#endif


//
// constants & macros for entire HW_LCDIF_VDCTRL3 register
//

#define HW_LCDIF_VDCTRL3_ADDR      (REGS_LCDIF_BASE + 0x00000060)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_VDCTRL3           (*(volatile hw_lcdif_vdctrl3_t *) HW_LCDIF_VDCTRL3_ADDR)
#define HW_LCDIF_VDCTRL3_RD()      (HW_LCDIF_VDCTRL3.U)
#define HW_LCDIF_VDCTRL3_WR(v)     (HW_LCDIF_VDCTRL3.U = (v))
#define HW_LCDIF_VDCTRL3_SET(v)    (HW_LCDIF_VDCTRL3_WR(HW_LCDIF_VDCTRL3_RD() |  (v)))
#define HW_LCDIF_VDCTRL3_CLR(v)    (HW_LCDIF_VDCTRL3_WR(HW_LCDIF_VDCTRL3_RD() & ~(v)))
#define HW_LCDIF_VDCTRL3_TOG(v)    (HW_LCDIF_VDCTRL3_WR(HW_LCDIF_VDCTRL3_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_VDCTRL3 bitfields
//

//--- Register HW_LCDIF_VDCTRL3, field SYNC_SIGNALS_ON

#define BP_LCDIF_VDCTRL3_SYNC_SIGNALS_ON      24
#define BM_LCDIF_VDCTRL3_SYNC_SIGNALS_ON      0x01000000

#define BF_LCDIF_VDCTRL3_SYNC_SIGNALS_ON(v)   (((v) << 24) & BM_LCDIF_VDCTRL3_SYNC_SIGNALS_ON)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL3_SYNC_SIGNALS_ON(v)   BF_CS1(LCDIF_VDCTRL3, SYNC_SIGNALS_ON, v)
#endif

//--- Register HW_LCDIF_VDCTRL3, field HORIZONTAL_WAIT_CNT

#define BP_LCDIF_VDCTRL3_HORIZONTAL_WAIT_CNT      12
#define BM_LCDIF_VDCTRL3_HORIZONTAL_WAIT_CNT      0x00FFF000

#define BF_LCDIF_VDCTRL3_HORIZONTAL_WAIT_CNT(v)   (((v) << 12) & BM_LCDIF_VDCTRL3_HORIZONTAL_WAIT_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL3_HORIZONTAL_WAIT_CNT(v)   BF_CS1(LCDIF_VDCTRL3, HORIZONTAL_WAIT_CNT, v)
#endif

//--- Register HW_LCDIF_VDCTRL3, field VERTICAL_WAIT_CNT

#define BP_LCDIF_VDCTRL3_VERTICAL_WAIT_CNT      0
#define BM_LCDIF_VDCTRL3_VERTICAL_WAIT_CNT      0x000001FF

#define BF_LCDIF_VDCTRL3_VERTICAL_WAIT_CNT(v)   (((v) << 0) & BM_LCDIF_VDCTRL3_VERTICAL_WAIT_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_VDCTRL3_VERTICAL_WAIT_CNT(v)   BF_CS1(LCDIF_VDCTRL3, VERTICAL_WAIT_CNT, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DVICTRL0 - Digital Video Interface Control0 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned V_LINES_CNT     : 10;
        unsigned H_BLANKING_CNT  : 10;
        unsigned H_ACTIVE_CNT    : 11;
        unsigned RSRVD0          :  1;
    } B;
} hw_lcdif_dvictrl0_t;
#endif


//
// constants & macros for entire HW_LCDIF_DVICTRL0 register
//

#define HW_LCDIF_DVICTRL0_ADDR      (REGS_LCDIF_BASE + 0x00000070)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DVICTRL0           (*(volatile hw_lcdif_dvictrl0_t *) HW_LCDIF_DVICTRL0_ADDR)
#define HW_LCDIF_DVICTRL0_RD()      (HW_LCDIF_DVICTRL0.U)
#define HW_LCDIF_DVICTRL0_WR(v)     (HW_LCDIF_DVICTRL0.U = (v))
#define HW_LCDIF_DVICTRL0_SET(v)    (HW_LCDIF_DVICTRL0_WR(HW_LCDIF_DVICTRL0_RD() |  (v)))
#define HW_LCDIF_DVICTRL0_CLR(v)    (HW_LCDIF_DVICTRL0_WR(HW_LCDIF_DVICTRL0_RD() & ~(v)))
#define HW_LCDIF_DVICTRL0_TOG(v)    (HW_LCDIF_DVICTRL0_WR(HW_LCDIF_DVICTRL0_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_DVICTRL0 bitfields
//

//--- Register HW_LCDIF_DVICTRL0, field H_ACTIVE_CNT

#define BP_LCDIF_DVICTRL0_H_ACTIVE_CNT      20
#define BM_LCDIF_DVICTRL0_H_ACTIVE_CNT      0x7FF00000

#define BF_LCDIF_DVICTRL0_H_ACTIVE_CNT(v)   (((v) << 20) & BM_LCDIF_DVICTRL0_H_ACTIVE_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL0_H_ACTIVE_CNT(v)   BF_CS1(LCDIF_DVICTRL0, H_ACTIVE_CNT, v)
#endif

//--- Register HW_LCDIF_DVICTRL0, field H_BLANKING_CNT

#define BP_LCDIF_DVICTRL0_H_BLANKING_CNT      10
#define BM_LCDIF_DVICTRL0_H_BLANKING_CNT      0x000FFC00

#define BF_LCDIF_DVICTRL0_H_BLANKING_CNT(v)   (((v) << 10) & BM_LCDIF_DVICTRL0_H_BLANKING_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL0_H_BLANKING_CNT(v)   BF_CS1(LCDIF_DVICTRL0, H_BLANKING_CNT, v)
#endif

//--- Register HW_LCDIF_DVICTRL0, field V_LINES_CNT

#define BP_LCDIF_DVICTRL0_V_LINES_CNT      0
#define BM_LCDIF_DVICTRL0_V_LINES_CNT      0x000003FF

#define BF_LCDIF_DVICTRL0_V_LINES_CNT(v)   (((v) << 0) & BM_LCDIF_DVICTRL0_V_LINES_CNT)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL0_V_LINES_CNT(v)   BF_CS1(LCDIF_DVICTRL0, V_LINES_CNT, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DVICTRL1 - Digital Video Interface Control1 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned F2_START_LINE  : 10;
        unsigned F1_END_LINE    : 10;
        unsigned F1_START_LINE  : 10;
        unsigned RSRVD1         :  2;
    } B;
} hw_lcdif_dvictrl1_t;
#endif


//
// constants & macros for entire HW_LCDIF_DVICTRL1 register
//

#define HW_LCDIF_DVICTRL1_ADDR      (REGS_LCDIF_BASE + 0x00000080)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DVICTRL1           (*(volatile hw_lcdif_dvictrl1_t *) HW_LCDIF_DVICTRL1_ADDR)
#define HW_LCDIF_DVICTRL1_RD()      (HW_LCDIF_DVICTRL1.U)
#define HW_LCDIF_DVICTRL1_WR(v)     (HW_LCDIF_DVICTRL1.U = (v))
#define HW_LCDIF_DVICTRL1_SET(v)    (HW_LCDIF_DVICTRL1_WR(HW_LCDIF_DVICTRL1_RD() |  (v)))
#define HW_LCDIF_DVICTRL1_CLR(v)    (HW_LCDIF_DVICTRL1_WR(HW_LCDIF_DVICTRL1_RD() & ~(v)))
#define HW_LCDIF_DVICTRL1_TOG(v)    (HW_LCDIF_DVICTRL1_WR(HW_LCDIF_DVICTRL1_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_DVICTRL1 bitfields
//

//--- Register HW_LCDIF_DVICTRL1, field F1_START_LINE

#define BP_LCDIF_DVICTRL1_F1_START_LINE      20
#define BM_LCDIF_DVICTRL1_F1_START_LINE      0x3FF00000

#define BF_LCDIF_DVICTRL1_F1_START_LINE(v)   (((v) << 20) & BM_LCDIF_DVICTRL1_F1_START_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL1_F1_START_LINE(v)   BF_CS1(LCDIF_DVICTRL1, F1_START_LINE, v)
#endif

//--- Register HW_LCDIF_DVICTRL1, field F1_END_LINE

#define BP_LCDIF_DVICTRL1_F1_END_LINE      10
#define BM_LCDIF_DVICTRL1_F1_END_LINE      0x000FFC00

#define BF_LCDIF_DVICTRL1_F1_END_LINE(v)   (((v) << 10) & BM_LCDIF_DVICTRL1_F1_END_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL1_F1_END_LINE(v)   BF_CS1(LCDIF_DVICTRL1, F1_END_LINE, v)
#endif

//--- Register HW_LCDIF_DVICTRL1, field F2_START_LINE

#define BP_LCDIF_DVICTRL1_F2_START_LINE      0
#define BM_LCDIF_DVICTRL1_F2_START_LINE      0x000003FF

#define BF_LCDIF_DVICTRL1_F2_START_LINE(v)   (((v) << 0) & BM_LCDIF_DVICTRL1_F2_START_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL1_F2_START_LINE(v)   BF_CS1(LCDIF_DVICTRL1, F2_START_LINE, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DVICTRL2 - Digital Video Interface Control2 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned V1_BLANK_END_LINE    : 10;
        unsigned V1_BLANK_START_LINE  : 10;
        unsigned F2_END_LINE          : 10;
        unsigned RSRVD1               :  2;
    } B;
} hw_lcdif_dvictrl2_t;
#endif


//
// constants & macros for entire HW_LCDIF_DVICTRL2 register
//

#define HW_LCDIF_DVICTRL2_ADDR      (REGS_LCDIF_BASE + 0x00000090)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DVICTRL2           (*(volatile hw_lcdif_dvictrl2_t *) HW_LCDIF_DVICTRL2_ADDR)
#define HW_LCDIF_DVICTRL2_RD()      (HW_LCDIF_DVICTRL2.U)
#define HW_LCDIF_DVICTRL2_WR(v)     (HW_LCDIF_DVICTRL2.U = (v))
#define HW_LCDIF_DVICTRL2_SET(v)    (HW_LCDIF_DVICTRL2_WR(HW_LCDIF_DVICTRL2_RD() |  (v)))
#define HW_LCDIF_DVICTRL2_CLR(v)    (HW_LCDIF_DVICTRL2_WR(HW_LCDIF_DVICTRL2_RD() & ~(v)))
#define HW_LCDIF_DVICTRL2_TOG(v)    (HW_LCDIF_DVICTRL2_WR(HW_LCDIF_DVICTRL2_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_DVICTRL2 bitfields
//

//--- Register HW_LCDIF_DVICTRL2, field F2_END_LINE

#define BP_LCDIF_DVICTRL2_F2_END_LINE      20
#define BM_LCDIF_DVICTRL2_F2_END_LINE      0x3FF00000

#define BF_LCDIF_DVICTRL2_F2_END_LINE(v)   (((v) << 20) & BM_LCDIF_DVICTRL2_F2_END_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL2_F2_END_LINE(v)   BF_CS1(LCDIF_DVICTRL2, F2_END_LINE, v)
#endif

//--- Register HW_LCDIF_DVICTRL2, field V1_BLANK_START_LINE

#define BP_LCDIF_DVICTRL2_V1_BLANK_START_LINE      10
#define BM_LCDIF_DVICTRL2_V1_BLANK_START_LINE      0x000FFC00

#define BF_LCDIF_DVICTRL2_V1_BLANK_START_LINE(v)   (((v) << 10) & BM_LCDIF_DVICTRL2_V1_BLANK_START_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL2_V1_BLANK_START_LINE(v)   BF_CS1(LCDIF_DVICTRL2, V1_BLANK_START_LINE, v)
#endif

//--- Register HW_LCDIF_DVICTRL2, field V1_BLANK_END_LINE

#define BP_LCDIF_DVICTRL2_V1_BLANK_END_LINE      0
#define BM_LCDIF_DVICTRL2_V1_BLANK_END_LINE      0x000003FF

#define BF_LCDIF_DVICTRL2_V1_BLANK_END_LINE(v)   (((v) << 0) & BM_LCDIF_DVICTRL2_V1_BLANK_END_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL2_V1_BLANK_END_LINE(v)   BF_CS1(LCDIF_DVICTRL2, V1_BLANK_END_LINE, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DVICTRL3 - Digital Video Interface Control3 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned V2_BLANK_END_LINE    : 10;
        unsigned RSRVD0               :  6;
        unsigned V2_BLANK_START_LINE  : 10;
        unsigned RSRVD1               :  6;
    } B;
} hw_lcdif_dvictrl3_t;
#endif


//
// constants & macros for entire HW_LCDIF_DVICTRL3 register
//

#define HW_LCDIF_DVICTRL3_ADDR      (REGS_LCDIF_BASE + 0x000000A0)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DVICTRL3           (*(volatile hw_lcdif_dvictrl3_t *) HW_LCDIF_DVICTRL3_ADDR)
#define HW_LCDIF_DVICTRL3_RD()      (HW_LCDIF_DVICTRL3.U)
#define HW_LCDIF_DVICTRL3_WR(v)     (HW_LCDIF_DVICTRL3.U = (v))
#define HW_LCDIF_DVICTRL3_SET(v)    (HW_LCDIF_DVICTRL3_WR(HW_LCDIF_DVICTRL3_RD() |  (v)))
#define HW_LCDIF_DVICTRL3_CLR(v)    (HW_LCDIF_DVICTRL3_WR(HW_LCDIF_DVICTRL3_RD() & ~(v)))
#define HW_LCDIF_DVICTRL3_TOG(v)    (HW_LCDIF_DVICTRL3_WR(HW_LCDIF_DVICTRL3_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_DVICTRL3 bitfields
//

//--- Register HW_LCDIF_DVICTRL3, field V2_BLANK_START_LINE

#define BP_LCDIF_DVICTRL3_V2_BLANK_START_LINE      16
#define BM_LCDIF_DVICTRL3_V2_BLANK_START_LINE      0x03FF0000

#define BF_LCDIF_DVICTRL3_V2_BLANK_START_LINE(v)   (((v) << 16) & BM_LCDIF_DVICTRL3_V2_BLANK_START_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL3_V2_BLANK_START_LINE(v)   BF_CS1(LCDIF_DVICTRL3, V2_BLANK_START_LINE, v)
#endif

//--- Register HW_LCDIF_DVICTRL3, field V2_BLANK_END_LINE

#define BP_LCDIF_DVICTRL3_V2_BLANK_END_LINE      0
#define BM_LCDIF_DVICTRL3_V2_BLANK_END_LINE      0x000003FF

#define BF_LCDIF_DVICTRL3_V2_BLANK_END_LINE(v)   (((v) << 0) & BM_LCDIF_DVICTRL3_V2_BLANK_END_LINE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DVICTRL3_V2_BLANK_END_LINE(v)   BF_CS1(LCDIF_DVICTRL3, V2_BLANK_END_LINE, v)
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DATA - LCD Interface Data Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        reg8_t   DATA_ZERO;
        reg8_t   DATA_ONE;
        reg8_t   DATA_TWO;
        reg8_t   DATA_THREE;
    } B;
} hw_lcdif_data_t;
#endif


//
// constants & macros for entire HW_LCDIF_DATA register
//

#define HW_LCDIF_DATA_ADDR      (REGS_LCDIF_BASE + 0x000000B0)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DATA           (*(volatile hw_lcdif_data_t *) HW_LCDIF_DATA_ADDR)
#define HW_LCDIF_DATA_RD()      (HW_LCDIF_DATA.U)
#define HW_LCDIF_DATA_WR(v)     (HW_LCDIF_DATA.U = (v))
#define HW_LCDIF_DATA_SET(v)    (HW_LCDIF_DATA_WR(HW_LCDIF_DATA_RD() |  (v)))
#define HW_LCDIF_DATA_CLR(v)    (HW_LCDIF_DATA_WR(HW_LCDIF_DATA_RD() & ~(v)))
#define HW_LCDIF_DATA_TOG(v)    (HW_LCDIF_DATA_WR(HW_LCDIF_DATA_RD() ^  (v)))
#endif


//
// constants & macros for individual HW_LCDIF_DATA bitfields
//

//--- Register HW_LCDIF_DATA, field DATA_THREE

#define BP_LCDIF_DATA_DATA_THREE      24
#define BM_LCDIF_DATA_DATA_THREE      0xFF000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_DATA_DATA_THREE(v)   ((((reg32_t) v) << 24) & BM_LCDIF_DATA_DATA_THREE)
#else
#define BF_LCDIF_DATA_DATA_THREE(v)   (((v) << 24) & BM_LCDIF_DATA_DATA_THREE)
#endif

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DATA_DATA_THREE(v)   (HW_LCDIF_DATA.B.DATA_THREE = (v))
#endif

//--- Register HW_LCDIF_DATA, field DATA_TWO

#define BP_LCDIF_DATA_DATA_TWO      16
#define BM_LCDIF_DATA_DATA_TWO      0x00FF0000

#define BF_LCDIF_DATA_DATA_TWO(v)   (((v) << 16) & BM_LCDIF_DATA_DATA_TWO)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DATA_DATA_TWO(v)   (HW_LCDIF_DATA.B.DATA_TWO = (v))
#endif

//--- Register HW_LCDIF_DATA, field DATA_ONE

#define BP_LCDIF_DATA_DATA_ONE      8
#define BM_LCDIF_DATA_DATA_ONE      0x0000FF00

#define BF_LCDIF_DATA_DATA_ONE(v)   (((v) << 8) & BM_LCDIF_DATA_DATA_ONE)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DATA_DATA_ONE(v)   (HW_LCDIF_DATA.B.DATA_ONE = (v))
#endif

//--- Register HW_LCDIF_DATA, field DATA_ZERO

#define BP_LCDIF_DATA_DATA_ZERO      0
#define BM_LCDIF_DATA_DATA_ZERO      0x000000FF

#define BF_LCDIF_DATA_DATA_ZERO(v)   (((v) << 0) & BM_LCDIF_DATA_DATA_ZERO)

#ifndef __LANGUAGE_ASM__
#define BW_LCDIF_DATA_DATA_ZERO(v)   (HW_LCDIF_DATA.B.DATA_ZERO = (v))
#endif


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_STAT - LCD Interface Status Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        unsigned RSRVD0             : 24;
        unsigned DVI_CURRENT_FIELD  :  1;
        unsigned BUSY               :  1;
        unsigned TXFIFO_EMPTY       :  1;
        unsigned TXFIFO_FULL        :  1;
        unsigned RXFIFO_EMPTY       :  1;
        unsigned RXFIFO_FULL        :  1;
        unsigned DMA_REQ            :  1;
        unsigned PRESENT            :  1;
    } B;
} hw_lcdif_stat_t;
#endif


//
// constants & macros for entire HW_LCDIF_STAT register
//

#define HW_LCDIF_STAT_ADDR      (REGS_LCDIF_BASE + 0x000000C0)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_STAT           (*(volatile hw_lcdif_stat_t *) HW_LCDIF_STAT_ADDR)
#define HW_LCDIF_STAT_RD()      (HW_LCDIF_STAT.U)
#endif


//
// constants & macros for individual HW_LCDIF_STAT bitfields
//

//--- Register HW_LCDIF_STAT, field PRESENT

#define BP_LCDIF_STAT_PRESENT      31
#define BM_LCDIF_STAT_PRESENT      0x80000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_STAT_PRESENT(v)   ((((reg32_t) v) << 31) & BM_LCDIF_STAT_PRESENT)
#else
#define BF_LCDIF_STAT_PRESENT(v)   (((v) << 31) & BM_LCDIF_STAT_PRESENT)
#endif

//--- Register HW_LCDIF_STAT, field DMA_REQ

#define BP_LCDIF_STAT_DMA_REQ      30
#define BM_LCDIF_STAT_DMA_REQ      0x40000000

#define BF_LCDIF_STAT_DMA_REQ(v)   (((v) << 30) & BM_LCDIF_STAT_DMA_REQ)

//--- Register HW_LCDIF_STAT, field RXFIFO_FULL

#define BP_LCDIF_STAT_RXFIFO_FULL      29
#define BM_LCDIF_STAT_RXFIFO_FULL      0x20000000

#define BF_LCDIF_STAT_RXFIFO_FULL(v)   (((v) << 29) & BM_LCDIF_STAT_RXFIFO_FULL)

//--- Register HW_LCDIF_STAT, field RXFIFO_EMPTY

#define BP_LCDIF_STAT_RXFIFO_EMPTY      28
#define BM_LCDIF_STAT_RXFIFO_EMPTY      0x10000000

#define BF_LCDIF_STAT_RXFIFO_EMPTY(v)   (((v) << 28) & BM_LCDIF_STAT_RXFIFO_EMPTY)

//--- Register HW_LCDIF_STAT, field TXFIFO_FULL

#define BP_LCDIF_STAT_TXFIFO_FULL      27
#define BM_LCDIF_STAT_TXFIFO_FULL      0x08000000

#define BF_LCDIF_STAT_TXFIFO_FULL(v)   (((v) << 27) & BM_LCDIF_STAT_TXFIFO_FULL)

//--- Register HW_LCDIF_STAT, field TXFIFO_EMPTY

#define BP_LCDIF_STAT_TXFIFO_EMPTY      26
#define BM_LCDIF_STAT_TXFIFO_EMPTY      0x04000000

#define BF_LCDIF_STAT_TXFIFO_EMPTY(v)   (((v) << 26) & BM_LCDIF_STAT_TXFIFO_EMPTY)

//--- Register HW_LCDIF_STAT, field BUSY

#define BP_LCDIF_STAT_BUSY      25
#define BM_LCDIF_STAT_BUSY      0x02000000

#define BF_LCDIF_STAT_BUSY(v)   (((v) << 25) & BM_LCDIF_STAT_BUSY)

//--- Register HW_LCDIF_STAT, field DVI_CURRENT_FIELD

#define BP_LCDIF_STAT_DVI_CURRENT_FIELD      24
#define BM_LCDIF_STAT_DVI_CURRENT_FIELD      0x01000000

#define BF_LCDIF_STAT_DVI_CURRENT_FIELD(v)   (((v) << 24) & BM_LCDIF_STAT_DVI_CURRENT_FIELD)


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_VERSION - LCD Interface Version  Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        reg16_t  STEP;
        reg8_t   MINOR;
        reg8_t   MAJOR;
    } B;
} hw_lcdif_version_t;
#endif


//
// constants & macros for entire HW_LCDIF_VERSION register
//

#define HW_LCDIF_VERSION_ADDR      (REGS_LCDIF_BASE + 0x000000D0)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_VERSION           (*(volatile hw_lcdif_version_t *) HW_LCDIF_VERSION_ADDR)
#define HW_LCDIF_VERSION_RD()      (HW_LCDIF_VERSION.U)
#endif


//
// constants & macros for individual HW_LCDIF_VERSION bitfields
//

//--- Register HW_LCDIF_VERSION, field MAJOR

#define BP_LCDIF_VERSION_MAJOR      24
#define BM_LCDIF_VERSION_MAJOR      0xFF000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_VERSION_MAJOR(v)   ((((reg32_t) v) << 24) & BM_LCDIF_VERSION_MAJOR)
#else
#define BF_LCDIF_VERSION_MAJOR(v)   (((v) << 24) & BM_LCDIF_VERSION_MAJOR)
#endif

//--- Register HW_LCDIF_VERSION, field MINOR

#define BP_LCDIF_VERSION_MINOR      16
#define BM_LCDIF_VERSION_MINOR      0x00FF0000

#define BF_LCDIF_VERSION_MINOR(v)   (((v) << 16) & BM_LCDIF_VERSION_MINOR)

//--- Register HW_LCDIF_VERSION, field STEP

#define BP_LCDIF_VERSION_STEP      0
#define BM_LCDIF_VERSION_STEP      0x0000FFFF

#define BF_LCDIF_VERSION_STEP(v)   (((v) << 0) & BM_LCDIF_VERSION_STEP)


////////////////////////////////////////////////////////////////////////////////
//// HW_LCDIF_DEBUG0 - LCD Interface Debug0 Register
////////////////////////////////////////////////////////////////////////////////

#ifndef __LANGUAGE_ASM__
typedef union
{
    reg32_t  U;
    struct
    {
        reg16_t  DATA_COUNT;
        unsigned CUR_STATE                :  7;
        unsigned EMPTY_WORD               :  1;
        unsigned CUR_FRAME_TX             :  1;
        unsigned VSYNC                    :  1;
        unsigned HSYNC                    :  1;
        unsigned ENABLE                   :  1;
        unsigned DMACMDKICK               :  1;
        unsigned SYNC_SIGNALS_ON_REG      :  1;
        unsigned WAIT_FOR_VSYNC_EDGE_OUT  :  1;
        unsigned STREAMING_END_DETECTED   :  1;
    } B;
} hw_lcdif_debug0_t;
#endif


//
// constants & macros for entire HW_LCDIF_DEBUG0 register
//

#define HW_LCDIF_DEBUG0_ADDR      (REGS_LCDIF_BASE + 0x000000E0)

#ifndef __LANGUAGE_ASM__
#define HW_LCDIF_DEBUG0           (*(volatile hw_lcdif_debug0_t *) HW_LCDIF_DEBUG0_ADDR)
#define HW_LCDIF_DEBUG0_RD()      (HW_LCDIF_DEBUG0.U)
#endif


//
// constants & macros for individual HW_LCDIF_DEBUG0 bitfields
//

//--- Register HW_LCDIF_DEBUG0, field STREAMING_END_DETECTED

#define BP_LCDIF_DEBUG0_STREAMING_END_DETECTED      31
#define BM_LCDIF_DEBUG0_STREAMING_END_DETECTED      0x80000000

#ifndef __LANGUAGE_ASM__
#define BF_LCDIF_DEBUG0_STREAMING_END_DETECTED(v)   ((((reg32_t) v) << 31) & BM_LCDIF_DEBUG0_STREAMING_END_DETECTED)
#else
#define BF_LCDIF_DEBUG0_STREAMING_END_DETECTED(v)   (((v) << 31) & BM_LCDIF_DEBUG0_STREAMING_END_DETECTED)
#endif

//--- Register HW_LCDIF_DEBUG0, field WAIT_FOR_VSYNC_EDGE_OUT

#define BP_LCDIF_DEBUG0_WAIT_FOR_VSYNC_EDGE_OUT      30
#define BM_LCDIF_DEBUG0_WAIT_FOR_VSYNC_EDGE_OUT      0x40000000

#define BF_LCDIF_DEBUG0_WAIT_FOR_VSYNC_EDGE_OUT(v)   (((v) << 30) & BM_LCDIF_DEBUG0_WAIT_FOR_VSYNC_EDGE_OUT)

//--- Register HW_LCDIF_DEBUG0, field SYNC_SIGNALS_ON_REG

#define BP_LCDIF_DEBUG0_SYNC_SIGNALS_ON_REG      29
#define BM_LCDIF_DEBUG0_SYNC_SIGNALS_ON_REG      0x20000000

#define BF_LCDIF_DEBUG0_SYNC_SIGNALS_ON_REG(v)   (((v) << 29) & BM_LCDIF_DEBUG0_SYNC_SIGNALS_ON_REG)

//--- Register HW_LCDIF_DEBUG0, field DMACMDKICK

#define BP_LCDIF_DEBUG0_DMACMDKICK      28
#define BM_LCDIF_DEBUG0_DMACMDKICK      0x10000000

#define BF_LCDIF_DEBUG0_DMACMDKICK(v)   (((v) << 28) & BM_LCDIF_DEBUG0_DMACMDKICK)

//--- Register HW_LCDIF_DEBUG0, field ENABLE

#define BP_LCDIF_DEBUG0_ENABLE      27
#define BM_LCDIF_DEBUG0_ENABLE      0x08000000

#define BF_LCDIF_DEBUG0_ENABLE(v)   (((v) << 27) & BM_LCDIF_DEBUG0_ENABLE)

//--- Register HW_LCDIF_DEBUG0, field HSYNC

#define BP_LCDIF_DEBUG0_HSYNC      26
#define BM_LCDIF_DEBUG0_HSYNC      0x04000000

#define BF_LCDIF_DEBUG0_HSYNC(v)   (((v) << 26) & BM_LCDIF_DEBUG0_HSYNC)

//--- Register HW_LCDIF_DEBUG0, field VSYNC

#define BP_LCDIF_DEBUG0_VSYNC      25
#define BM_LCDIF_DEBUG0_VSYNC      0x02000000

#define BF_LCDIF_DEBUG0_VSYNC(v)   (((v) << 25) & BM_LCDIF_DEBUG0_VSYNC)

//--- Register HW_LCDIF_DEBUG0, field CUR_FRAME_TX

#define BP_LCDIF_DEBUG0_CUR_FRAME_TX      24
#define BM_LCDIF_DEBUG0_CUR_FRAME_TX      0x01000000

#define BF_LCDIF_DEBUG0_CUR_FRAME_TX(v)   (((v) << 24) & BM_LCDIF_DEBUG0_CUR_FRAME_TX)

//--- Register HW_LCDIF_DEBUG0, field EMPTY_WORD

#define BP_LCDIF_DEBUG0_EMPTY_WORD      23
#define BM_LCDIF_DEBUG0_EMPTY_WORD      0x00800000

#define BF_LCDIF_DEBUG0_EMPTY_WORD(v)   (((v) << 23) & BM_LCDIF_DEBUG0_EMPTY_WORD)

//--- Register HW_LCDIF_DEBUG0, field CUR_STATE

#define BP_LCDIF_DEBUG0_CUR_STATE      16
#define BM_LCDIF_DEBUG0_CUR_STATE      0x007F0000

#define BF_LCDIF_DEBUG0_CUR_STATE(v)   (((v) << 16) & BM_LCDIF_DEBUG0_CUR_STATE)

//--- Register HW_LCDIF_DEBUG0, field DATA_COUNT

#define BP_LCDIF_DEBUG0_DATA_COUNT      0
#define BM_LCDIF_DEBUG0_DATA_COUNT      0x0000FFFF

#define BF_LCDIF_DEBUG0_DATA_COUNT(v)   (((v) << 0) & BM_LCDIF_DEBUG0_DATA_COUNT)


#endif // _REGSLCDIF_H

////////////////////////////////////////////////////////////////////////////////
